# server configurations
server:
  host: "http://127.0.0.1"
  port: 8082

# oauth configurations
oauth:
  rsa_bits: 2048
  audience: "important-resource-server"
  issuer: "http://localhost:8082"
  jwt_ttl: "1h"
  jwks: "/jwks"

# SPNEGO configurations
spnego:
  volume: "/scorpio"
  keytab: "scorpio-oauth.keytab"
  realm: "KRB.SCORPIO.ORDINARYCOMPUTING.COM"
  service_principal_name: "scorpio/oauth.scorpio.ordinarycomputing.com@KRB.SCORPIO.ORDINARYCOMPUTING.COM"

# PKI configuration
pki:
  endpoint: "http://ca.scorpio.ordinarycomputing.com/spnego"
  service_principal_name: "scorpio/ca.scorpio.ordinarycomputing.com@KRB.SCORPIO.ORDINARYCOMPUTING.COM"
  sans:
    - "oauth.scorpio.ordinarycomputing.com"