# server configurations
server:
  host: "http://127.0.0.1"
  port: 8081

# redis configurations
persistence:
  enabled: false
  host: "db-valkey-nyc1-scorpio-do-user-16782644-0.l.db.ondigitalocean.com"
  port: 25061
  user: "default"
  path: "/etc/scorpio-secret/password"
  database: 1

# oauth configurations
oauth:
  rsa_bits: 2048
  audience: "important-resource-server"
  issuer: "https://identity.io"
  jwt_ttl: "60m"
  jwks: "/jwks"

# SPNEGO configurations
spnego:
  volume: "/scorpio"
  keytab: "scorpio-oauth.keytab"
  realm: "KRB.SCORPIO.ORDINARYCOMPUTING.COM"
  service_principal_name: "scorpio/oauth.scorpio.ordinarycomputing.com@KRB.SCORPIO.ORDINARYCOMPUTING.COM"

# PKI configuration
pki:
  endpoint: "http://ca.scorpio.ordinarycomputing.com/spnego"
  sans:
    - "oauth.scorpio.ordinarycomputing.com"