# server configurations
server:
  host: "http://127.0.0.1"
  port: 8081

# oauth configurations
oauth:
  rsa_bits: 2048
  audience: "important-resource-server"
  issuer: "https://identity.io"
  jwt_ttl: "60m"
  jwks: "/jwks"