info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: a Go OAuth2 issuer implementation
  license:
    name: MIT
    url: https://mit-license.org
  termsOfService: http://swagger.io/terms/
  title: Scorpio OAuth
  version: "1.0"
paths:
  /authorize:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Accepts response_type, client_id, and redirect_url parameters in
        application/x-www-form-urlencoded HTTP request
      parameters:
      - description: code
        in: query
        name: response_type
        required: true
        type: string
      - description: client identifier
        in: query
        name: client_id
        required: true
        type: string
      - description: target redirect URI
        in: query
        name: redirect_uri
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "300":
          description: Found
          schema:
            type: string
        "400":
          description: Bad Request - check your form params
          schema:
            type: string
        "415":
          description: Unsupported Media Type
          schema:
            type: string
      summary: Generates an authorization code as part of authorization code grant
      tags:
      - grant
swagger: "2.0"
